In [1]:
import pandas as pd 
data = pd.read_csv("Countries.csv")

In [3]:
#COUNTRY WITH THE HIGHEST POPULATION
data[data['population'] == data['population'].max()]

   country       country_long      currency capital_city  ...    democracy_type median_age political_leader           title
75   India  Republic of India  Indian rupee    New Delhi  ...  Flawed democracy       23.9    Narendra Modi  Prime Minister

[1 rows x 64 columns]

In [4]:
#CAPITAL OF THE COUNTRY WITH THE HIGHEST POPULATION
data[data['population'] == data['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [5]:
#WHICH COUNTRY HAS THE LEAST POPULATION
data[data['population'] == data['population'].min()]

    country country_long           currency capital_city  ... democracy_type median_age political_leader           title
179  Tuvalu       Tuvalu  Australian dollar     Funafuti  ...        Unknown       21.0    Kausea Natano  Prime Minister

[1 rows x 64 columns]

In [6]:
#CAPITAL OF THE COUNTRY WITH LEAST POPULATION
data[data['population'] == data['population'].min()]['capital_city']

179    Funafuti
Name: capital_city, dtype: object

In [11]:
#TOP 5 COUNTRIES WITH HIGHEST DEMOCRATIC SCORE
data.sort_values(by="democracy_score",ascending=False).head()

         country         country_long            currency  ... median_age     political_leader           title
127       Norway    Kingdom of Norway     Norwegian krone  ...       35.6         Erna Solberg  Prime Minister
74       Iceland  Republic of Iceland       Iceland krona  ...       32.1  Katrín Jakobsdóttir  Prime Minister
164       Sweden    Kingdom of Sweden       Swedish krona  ...       35.6        Stefan Löfven  Prime Minister
122  New Zealand          New Zealand  New Zealand dollar  ...       32.8       Jacinda Ardern  Prime Minister
46       Denmark   Kingdom of Denmark        Danish krone  ...       37.2    Mette Frederiksen  Prime Minister

[5 rows x 64 columns]

In [14]:
#total number of regions
tot_reg = data.value_counts("region").sum()
print(f"There are total {tot_reg} regions in this data frame")

There are total 194 regions in this data frame

In [22]:
#number of countries in eastern europe region 
count = data[data['region'] == 'Eastern Europe'].value_counts('country').sum()
print(f"There are total {count} countries in Eastern Europe")

There are total 10 countries in Eastern Europe

In [30]:
#political leader of the country with 2nd highest population
data.nlargest(2,columns='population').iloc[1]['political_leader']

'Xi Jinping'